### PR TITLE
Cache busting improvements for the application and cleaner build

### PR DESCRIPTION
**Pull request by lauslim12**
Hello!

I noticed that some of browsers (especially Safari and Edge) will still use the cached `index.html` file. Because of this, even though the JavaScript file has been re-hashed and re-compiled, the browser will still fetch the `index.html` from their own cache (this is the reason of the bug!). As a result, the bug appears again for some of the browsers 😅 (as the old `index.html` will still have the old `main.<hash>.js` file).

After googling for a day (😂), I propose another fix on top of the previous PR, and that is to use a `.htaccess` file to control web caching straight from the server. We will be using `Cache-Control`, `Pragma`, and `Expires` headers to control the web caching. The `.htaccess` file will only work on Apache Web Servers, and because I use Apache, `.htaccess` is what I use. The only file that will not be cached is only the `index.html` file, so every time a user opens the application, their browsers will always request for the `index.html` file. However, this will not affect our application's load speed, because the `index.html` file is only one or two kilobytes at best. The JavaScript will still be taken from the cache, unless if we bump the version number (then it will fetch the data again from our server), like I said before in my previous PR. Plus, I made it so the `.htaccess` file will force us to use HTTPS (which is again, a good practice).

Because of this fix, I believe we will not run into caching problems anymore, unless if you use nginx as your web server, then we're going to have to disable caching for nginx too. However, the logic should be the same (which is to never cache the `index.html` file). The `.htaccess` file will have no effect if we use them in a web server other than Apache, so I think it is fine if we leave it like that.

I also refactored the `webpack.config.js` file slightly. I replaced all of the hardcoded paths with the `path` library to make it cleaner. I also made it so when we built the app, all of the images will be stored in the `dist/images` folder, instead of simply the `dist` folder, to make it cleaner. Oh, and there is also a `CopyWebpackPlugin` dependency that I added to copy the `.htaccess` file into the distribution folder.

I have tested this PR and built it on [my web server and it works perfectly](http://genshin-gacha.nicholasdw.com/)! No caching for the `index.html`, while still keeping our cache of JavaScript file unless we bump our version number.

Hope it helps you and thank you!

### CODE REVIEW

**Comment by uzair-ashraf** [comment]
So unfortunately the problem with this approach is the fact that I am deploying another version of this site using github pages, and I'm not sure what github pages uses underneath the hood.  On my main ec2 instance I have the app deployed using Apache2, however I'll be redoing my server configuration soon and I'll be switching to nginx.

Not sure if this foils the plan, but it seems like most of the users are no longer experiencing the bug.

**Comment by lauslim12** [comment]
If most of the users are not experiencing this bug then it is a good news then! This is actually just a fix for Apache users, who knows if they might want to deploy it with an Apache web server 😅

Either way, the logic is still the same though, we have to disable caching for the `index.html` file to prevent unwanted things from happening.

I'm not sure about this, but I believe that GitHub Pages uses Jekyll as their server.

**Comment by uzair-ashraf** [comment]
@lauslim12 Sorry for the late responses, been busy with work and was out of town for a week.

AWS charged me $164 last month due to the amount of traffic and insane downloads of assets lol, so I switched to Github pages, indefinitely.

The configuration file will have to be different now to solve the caching issue.

**Comment by lauslim12** [comment]
Sure thing! I'll try to find a workaround, but when the Childe banner is done, try pushing it to GitHub Pages. If it busts the cache by itself, then perhaps we don't need this cache busting solution after all if we use GitHub Pages.

**Comment by uzair-ashraf** [comment]
sounds good! I'm working on the assets right now

**Comment by lauslim12** [comment]
I have checked the deployed version, it seems that GitHub Pages has done a great job in busting the `index.html` cache. This pull request is therefore not needed (as it is Apache exclusive).

Closing this pull request, thank you!

**Pull request closed without merging**
