### PR TITLE
Issue #22, Issue #28, Issue #37, Issue #41, Issue #45, Added a 5-star soft pity 

### PR DESCRIPTION
**Pull request by elebitzero**
Hey, you have a really cool project that feels a lot like doing pulls in Genshin and the UI looks clean, so I decided to try and fix some of the major issues with the probability so the pulls are more realistic/believable.

I have fixed the issues detailed below.  The logic for both past and present banners have been updated.   I ran and updated the mocha tests and ran the cypress tests all the tests are passing, except one that I removed because it is no longer applicable. See details below.

After doing some pulls on the app, it looks much closer to what you would expect to get when doing pulls in the game.

- Issue #22
- Issue #28
- Issue #37
- Issue #41
- Issue #45
- Added a 5-star soft pity on the 75th pull for standard and event banners and 65th pull for the weapon banner. With a 32% chance to get a 5 star at 75+ pulls.  Also fixed the counter to reset whenever a 5-star item is pulled for all banners.
-- Reference: https://www.reddit.com/r/Genshin_Impact/comments/jo9d9d/the_5_rate_is_not_uniform_06_there_is_a_soft_pity/
-- Reference: https://www.reddit.com/r/Genshin_Impact/comments/kdy1ky/everyone_is_misunderstanding_soft_pity/
- Changed the original attemptsCount variable to pityCounter and added back attemptsCount variable to just track the number of attempts. Fixed the soft pity counter in the Venti banner. Fixed the tests to check based on the correct 5-star pity logic.
- Moved some duplicate methods to Base-Gacha
- Simplified Roll to call rollOnce
- Corrected 4-star pity logic to only give guaranteed 4-star or higher if a 4-star was not pulled within the previous 9 pulls on the event, standard, and weapon banners (all except beginner's wish)
- 4-star pity timer is now separate from 5-star pity timer
- Added a pityCounter reset whenever a featured 5-star item is pulled on the weapon and event banners.
- Fixed reset function in app.jsx to reset attemptsCount, pityCount, soft pity states, and probability ranges back to initial values for displayed banners.
- Removed test case that tested the faulty 4-star pity logic that guaranteed a 4-star or higher on the 10th pull even if a 4 star was pulled within 9 pulls (tests for 4 or 5 star within 10 pulls still covered)
- Fixed the problem where featured 4-star pity doesn't activate after not getting a featured 4-star character in the character event banners and weapon banner.
- Moved all character event banner methods to base-gacha and improved the rollOnce method to take care of getting the rating of an item and deciding if a pull is featured or nonfeatured with the correct probability. 
- Simplified weapon banner to use more general base-gacha logic except for a few methods that needed to override

### CODE REVIEW

**Comment by elebitzero** [comment]
I added a few more changes, including a separate timer for the 4-star pity, and putting some of the repeated methods into Base-Gacha. The mocha and cypress tests checked out and the pulls still seem reasonable.

**Comment by uzair-ashraf** [comment]
Can you run the build script so I can deploy it? Thanks!

**Comment by elebitzero** [comment]
I ran the build script but then it had a problem running since I'm on Windows so I manually copied the files to carry out the rest of the command and after that, it looks good. I did a little more cleanup and reran mocha and cypress and both are passing.

**Comment by elebitzero** [comment]
Issue #37 is now fixed, I also reran the tests, and regenerated the production build. I manually tried the app out and I seemed to be getting pulls we can expect from the probabilities listed. Now it should be ready to deploy and merge.

**Comment by elebitzero** [comment]
BTW, it will be really simple to add new event banners in the future.  For example, this is the current event banner adrift-in-the-harbor.js

```
import BaseGacha from './base-gacha'
import drops from '../data/adrift-in-the-harbor.json'

export default class AdriftInTheHarbor extends BaseGacha {
  constructor() {
    super(drops)
  }
}
```
Now all the code is generic and is driven off the drop data.

**Comment by uzair-ashraf** [comment]
Jesus christ thats a lot of work lol, have you ran the tests on the rest of the changes?

**Comment by elebitzero** [comment]
I reran the tests on the rest of the changes, plus I manually did pulls and did some extra clean up after that and now it should be ready. The tests still checked out after those.  I'm getting more single 4-star ten pulls, with double 4-stars and triple 4-stars being rarer now.

**Comment by uzair-ashraf** [comment]
@elebitzero Hey dude, is there a reason you are no longer using the app version from the package.json? it's what we use to bust the cache, so you dont force the users to go back to the previous pity system

image

**Comment by elebitzero** [comment]
The version I added was to version the application state data. I put in logic to read the old version and save it in the new format as version 1 to add backward compatibility so users don't have to see errors for the first time they play with the app again.

**Comment by uzair-ashraf** [comment]
Gotcha @elebitzero sorry for the late response, I just got a new job so I've been all over the place. I really appreciate your help dude.

**Pull request merged**
