### PR TITLE
Add multi language support，and support Chinese translation

### PR DESCRIPTION
**Pull request by deepwzh**

### CODE REVIEW

**Comment by uzair-ashraf** [comment]
Hello, there will be an update in the pity system and we will be going from the staging branch. After I merge that PR, can you open a pull request to the staging branch?

**Comment by deepwzh** [comment]
OK. When you update, could you inform me here, then I will submit PR again.

**Comment by uzair-ashraf** [comment]
Okiedoke, will inform you here, will find out tomorrow if it is ready for staging

**Comment by deepwzh** [comment]
By the way, you can add the information of the new banner and then inform me. I will add the corresponding cn translation.

**Comment by uzair-ashraf** [comment]
@deepwzh My plan is to bring the new banner in this weekend with the changes that were added to staging, we can talk about translations after it's up 👍🏼 

Thank you for your patience, I'm currently in the middle of switching jobs so my plate is very full right now.

**Comment by uzair-ashraf** [comment]
@deepwzh the changes are on the staging branch right now, you can take a look at it. It's also live if you want to see it for yourself. I'm testing the waters to see if it fails or not, if it seems fine we can bring in your translation asap.

Question though, how would we handle the translations for future banners?

**Comment by deepwzh** [comment]
Hello,I am busy with some things recently.I will submit the pr soon.
As for the future translation, I want to open a specific issue to display the corresponding translation content in 1.4 and later versions. You only need to paste the corresponding content into the project file (dist/locales/zh_CN/translation.json).
ps:The translation of version 1.3 has been provided.

(Some of my expressions have been translated by translation software. There may be some inaccuracies.)

**Comment by uzair-ashraf** [comment]
@deepwzh Hi there deep, there was another update to staging, I was wondering if you can pull down the changes and see what is required to update?

**Comment by uzair-ashraf** [comment]
If you aren't able to pull it down I can grab an update and push it anyway, the details pages will stay in english though right?

**Pull request closed without merging**
